// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYsCyN9eTyZvpBXx0QZdxlUEgTqRXUkUM',
    appId: '1:1009771374510:web:07f7ab974de8aa9088ca3f',
    messagingSenderId: '1009771374510',
    projectId: 'taskpomo-65d34',
    authDomain: 'taskpomo-65d34.firebaseapp.com',
    storageBucket: 'taskpomo-65d34.firebasestorage.app',
    measurementId: 'G-DLW9R4CX8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0xfO0naB-iaELCMCaK3PJWvfYgiL7uvo',
    appId: '1:1009771374510:android:6c31f3741140ad5988ca3f',
    messagingSenderId: '1009771374510',
    projectId: 'taskpomo-65d34',
    storageBucket: 'taskpomo-65d34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTL1bWd67gtwhSTxYezBWUvwj4gl5dHJE',
    appId: '1:1009771374510:ios:01536f628567ed7d88ca3f',
    messagingSenderId: '1009771374510',
    projectId: 'taskpomo-65d34',
    storageBucket: 'taskpomo-65d34.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTL1bWd67gtwhSTxYezBWUvwj4gl5dHJE',
    appId: '1:1009771374510:ios:01536f628567ed7d88ca3f',
    messagingSenderId: '1009771374510',
    projectId: 'taskpomo-65d34',
    storageBucket: 'taskpomo-65d34.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
